version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 851725338327.dkr.ecr.ap-south-1.amazonaws.com
      - REPO_URI=851725338327.dkr.ecr.ap-south-1.amazonaws.com/angular-webapp-cicd
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPO_URI:$IMAGE_TAG .
      - docker tag $REPO_URI:$IMAGE_TAG $REPO_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $REPO_URI:$IMAGE_TAG
      - docker push $REPO_URI:latest
      - echo Writing image details to file...
      - echo $REPO_URI:$IMAGE_TAG > imageDetail.txt
      - echo Creating imagedefinitions.json file...
      - printf '[{"name":"angular-webapp-container","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imageDetail.txt
    - imagedefinitions.json
