version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - echo Building Angular app...
      - ng build --configuration=production
      - echo Building Docker image...
      - docker build -t angular-app .
      - docker tag angular-app:latest <aws_account_id>.dkr.ecr.<region>.amazonaws.com/angular-app:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - aws ecr get-login-password --region <region> | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.<region>.amazonaws.com
      - docker push <aws_account_id>.dkr.ecr.<region>.amazonaws.com/angular-app:latest
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
